<?php
/**
 * ChannelCatalogCategoryMappingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelCatalogCategoryMappingTest Class Doc Comment
 *
 * @category    Class */
// * @description Represent a mapping between a catalog category path and a channel category path.  The cost on this mapping can be applied.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelCatalogCategoryMappingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ChannelCatalogCategoryMapping"
     */
    public function testChannelCatalogCategoryMapping()
    {

    }

    /**
     * Test attribute "catalog_category_path"
     */
    public function testPropertyCatalogCategoryPath()
    {

    }

    /**
     * Test attribute "channel_category_path"
     */
    public function testPropertyChannelCategoryPath()
    {

    }

    /**
     * Test attribute "cost_value"
     */
    public function testPropertyCostValue()
    {

    }

}
