<?php
/**
 * StoreTrackingStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StoreTrackingStatusTest Class Doc Comment
 *
 * @category    Class */
// * @description StoreTrackingStatus
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoreTrackingStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "StoreTrackingStatus"
     */
    public function testStoreTrackingStatus()
    {

    }

    /**
     * Test attribute "click_synchronization_utc_date"
     */
    public function testPropertyClickSynchronizationUtcDate()
    {

    }

    /**
     * Test attribute "order_synchonization_utc_date"
     */
    public function testPropertyOrderSynchonizationUtcDate()
    {

    }

    /**
     * Test attribute "marketplace_order_synchonization_utc_date"
     */
    public function testPropertyMarketplaceOrderSynchonizationUtcDate()
    {

    }

}
