<?php
/**
 * HarvestOrderReporting
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * HarvestOrderReporting Class Doc Comment
 *
 * @category    Class
 * @description The reporting related to a harvest order operation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HarvestOrderReporting implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'harvestOrderReporting';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'execution_uuid' => '\Swagger\Client\Model\ExecutionUUID',
        'creation_utc_date' => '\DateTime',
        'processing_status' => 'string',
        'last_update_utc_date' => '\DateTime',
        'error_message' => 'string',
        'warning_message' => 'string',
        'beez_up_status' => '\Swagger\Client\Model\BeezUPOrderStatus',
        'marketplace_status' => 'string',
        'beez_up_forced_status' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'execution_uuid' => 'executionUUID',
        'creation_utc_date' => 'creationUtcDate',
        'processing_status' => 'processingStatus',
        'last_update_utc_date' => 'lastUpdateUtcDate',
        'error_message' => 'errorMessage',
        'warning_message' => 'warningMessage',
        'beez_up_status' => 'beezUPStatus',
        'marketplace_status' => 'marketplaceStatus',
        'beez_up_forced_status' => 'beezUPForcedStatus'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'execution_uuid' => 'setExecutionUuid',
        'creation_utc_date' => 'setCreationUtcDate',
        'processing_status' => 'setProcessingStatus',
        'last_update_utc_date' => 'setLastUpdateUtcDate',
        'error_message' => 'setErrorMessage',
        'warning_message' => 'setWarningMessage',
        'beez_up_status' => 'setBeezUpStatus',
        'marketplace_status' => 'setMarketplaceStatus',
        'beez_up_forced_status' => 'setBeezUpForcedStatus'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'execution_uuid' => 'getExecutionUuid',
        'creation_utc_date' => 'getCreationUtcDate',
        'processing_status' => 'getProcessingStatus',
        'last_update_utc_date' => 'getLastUpdateUtcDate',
        'error_message' => 'getErrorMessage',
        'warning_message' => 'getWarningMessage',
        'beez_up_status' => 'getBeezUpStatus',
        'marketplace_status' => 'getMarketplaceStatus',
        'beez_up_forced_status' => 'getBeezUpForcedStatus'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['execution_uuid'] = isset($data['execution_uuid']) ? $data['execution_uuid'] : null;
        $this->container['creation_utc_date'] = isset($data['creation_utc_date']) ? $data['creation_utc_date'] : null;
        $this->container['processing_status'] = isset($data['processing_status']) ? $data['processing_status'] : null;
        $this->container['last_update_utc_date'] = isset($data['last_update_utc_date']) ? $data['last_update_utc_date'] : null;
        $this->container['error_message'] = isset($data['error_message']) ? $data['error_message'] : null;
        $this->container['warning_message'] = isset($data['warning_message']) ? $data['warning_message'] : null;
        $this->container['beez_up_status'] = isset($data['beez_up_status']) ? $data['beez_up_status'] : null;
        $this->container['marketplace_status'] = isset($data['marketplace_status']) ? $data['marketplace_status'] : null;
        $this->container['beez_up_forced_status'] = isset($data['beez_up_forced_status']) ? $data['beez_up_forced_status'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets execution_uuid
     * @return \Swagger\Client\Model\ExecutionUUID
     */
    public function getExecutionUuid()
    {
        return $this->container['execution_uuid'];
    }

    /**
     * Sets execution_uuid
     * @param \Swagger\Client\Model\ExecutionUUID $execution_uuid
     * @return $this
     */
    public function setExecutionUuid($execution_uuid)
    {
        $this->container['execution_uuid'] = $execution_uuid;

        return $this;
    }

    /**
     * Gets creation_utc_date
     * @return \DateTime
     */
    public function getCreationUtcDate()
    {
        return $this->container['creation_utc_date'];
    }

    /**
     * Sets creation_utc_date
     * @param \DateTime $creation_utc_date The creation UTC date of the execution
     * @return $this
     */
    public function setCreationUtcDate($creation_utc_date)
    {
        $this->container['creation_utc_date'] = $creation_utc_date;

        return $this;
    }

    /**
     * Gets processing_status
     * @return string
     */
    public function getProcessingStatus()
    {
        return $this->container['processing_status'];
    }

    /**
     * Sets processing_status
     * @param string $processing_status The processing status of the execution
     * @return $this
     */
    public function setProcessingStatus($processing_status)
    {
        $this->container['processing_status'] = $processing_status;

        return $this;
    }

    /**
     * Gets last_update_utc_date
     * @return \DateTime
     */
    public function getLastUpdateUtcDate()
    {
        return $this->container['last_update_utc_date'];
    }

    /**
     * Sets last_update_utc_date
     * @param \DateTime $last_update_utc_date The last update UTC date of the execution
     * @return $this
     */
    public function setLastUpdateUtcDate($last_update_utc_date)
    {
        $this->container['last_update_utc_date'] = $last_update_utc_date;

        return $this;
    }

    /**
     * Gets error_message
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     * @param string $error_message The warning message during the execution
     * @return $this
     */
    public function setErrorMessage($error_message)
    {
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets warning_message
     * @return string
     */
    public function getWarningMessage()
    {
        return $this->container['warning_message'];
    }

    /**
     * Sets warning_message
     * @param string $warning_message The warning message during the execution
     * @return $this
     */
    public function setWarningMessage($warning_message)
    {
        $this->container['warning_message'] = $warning_message;

        return $this;
    }

    /**
     * Gets beez_up_status
     * @return \Swagger\Client\Model\BeezUPOrderStatus
     */
    public function getBeezUpStatus()
    {
        return $this->container['beez_up_status'];
    }

    /**
     * Sets beez_up_status
     * @param \Swagger\Client\Model\BeezUPOrderStatus $beez_up_status
     * @return $this
     */
    public function setBeezUpStatus($beez_up_status)
    {
        $this->container['beez_up_status'] = $beez_up_status;

        return $this;
    }

    /**
     * Gets marketplace_status
     * @return string
     */
    public function getMarketplaceStatus()
    {
        return $this->container['marketplace_status'];
    }

    /**
     * Sets marketplace_status
     * @param string $marketplace_status The order marketplace status
     * @return $this
     */
    public function setMarketplaceStatus($marketplace_status)
    {
        $this->container['marketplace_status'] = $marketplace_status;

        return $this;
    }

    /**
     * Gets beez_up_forced_status
     * @return string
     */
    public function getBeezUpForcedStatus()
    {
        return $this->container['beez_up_forced_status'];
    }

    /**
     * Sets beez_up_forced_status
     * @param string $beez_up_forced_status The marketplace order status forced by BeezUP during the order change oepration. This could happend when there is no status on the marketplace side.
     * @return $this
     */
    public function setBeezUpForcedStatus($beez_up_forced_status)
    {
        $this->container['beez_up_forced_status'] = $beez_up_forced_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


