<?php
/**
 * ContractStoreInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Customer
 *
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContractStoreInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Describe the store information related to the offer.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContractStoreInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ContractStoreInfo"
     */
    public function testContractStoreInfo()
    {

    }

    /**
     * Test attribute "store_count"
     */
    public function testPropertyStoreCount()
    {

    }

    /**
     * Test attribute "max_store_count"
     */
    public function testPropertyMaxStoreCount()
    {

    }

    /**
     * Test attribute "min_store_count"
     */
    public function testPropertyMinStoreCount()
    {

    }

    /**
     * Test attribute "owned_store_count"
     */
    public function testPropertyOwnedStoreCount()
    {

    }

    /**
     * Test attribute "additional_store_price"
     */
    public function testPropertyAdditionalStorePrice()
    {

    }

    /**
     * Test attribute "store_included"
     */
    public function testPropertyStoreIncluded()
    {

    }

}
