<?php
/**
 * LinksReactivateCurrentContractLinkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LinksReactivateCurrentContractLinkTest Class Doc Comment
 *
 * @category    Class */
// * @description LinksReactivateCurrentContractLink
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinksReactivateCurrentContractLinkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LinksReactivateCurrentContractLink"
     */
    public function testLinksReactivateCurrentContractLink()
    {

    }

    /**
     * Test attribute "doc_url"
     */
    public function testPropertyDocUrl()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {

    }

    /**
     * Test attribute "operation_id"
     */
    public function testPropertyOperationId()
    {

    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {

    }

    /**
     * Test attribute "parameters"
     */
    public function testPropertyParameters()
    {

    }

    /**
     * Test attribute "templated"
     */
    public function testPropertyTemplated()
    {

    }

    /**
     * Test attribute "info"
     */
    public function testPropertyInfo()
    {

    }

}
