<?php
/**
 * BeezUPCommonErrorSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplaces - Orders
 *
 * The features exposed in this API are centered around managing Orders harvested from your configured marketplaces.\\ This includes: - fetching current information (as known by BeezUP) for a single or multiple Orders, - requesting Order harvest to synchronize your marketplaces and BeezUP accounts, - changing BeezUP data and requesting changes to your marketplaces (accepting, shipping, etc), - configuring automatic changes to marketplace based our newly fetched data, - creating and exporting reports for your Orders.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BeezUPCommonErrorSummaryTest Class Doc Comment
 *
 * @category    Class */
// * @description BeezUPCommonErrorSummary
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BeezUPCommonErrorSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "BeezUPCommonErrorSummary"
     */
    public function testBeezUPCommonErrorSummary()
    {

    }

    /**
     * Test attribute "utc_date"
     */
    public function testPropertyUtcDate()
    {

    }

    /**
     * Test attribute "error_guid"
     */
    public function testPropertyErrorGuid()
    {

    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {

    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {

    }

    /**
     * Test attribute "technical_error_message"
     */
    public function testPropertyTechnicalErrorMessage()
    {

    }

    /**
     * Test attribute "exception_detail"
     */
    public function testPropertyExceptionDetail()
    {

    }

    /**
     * Test attribute "error_arguments"
     */
    public function testPropertyErrorArguments()
    {

    }

    /**
     * Test attribute "property_name"
     */
    public function testPropertyPropertyName()
    {

    }

    /**
     * Test attribute "property_value"
     */
    public function testPropertyPropertyValue()
    {

    }

    /**
     * Test attribute "object_name"
     */
    public function testPropertyObjectName()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

}
