<?php
/**
 * VariableModelInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Customer
 *
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VariableModelInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Internal usage: Old offer type. Describe the fix and variable model information
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VariableModelInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "VariableModelInfo"
     */
    public function testVariableModelInfo()
    {

    }

    /**
     * Test attribute "click_included_and_variable_prices"
     */
    public function testPropertyClickIncludedAndVariablePrices()
    {

    }

    /**
     * Test attribute "overflow_click_count"
     */
    public function testPropertyOverflowClickCount()
    {

    }

    /**
     * Test attribute "overflow_click_price"
     */
    public function testPropertyOverflowClickPrice()
    {

    }

}
